### ISSUE TITLE
Error Dapi  name is missing

### ISSUE THREAD

**Issue by NrmeenTomoum** [dapi-co/DapiConnect-iOS#3]
<img width="465" alt="Screen Shot 2020-09-20 at 5 19 25 PM" src="https://user-images.githubusercontent.com/19241793/93714829-70259000-fb65-11ea-90fb-d97b92527eb5.png">
Why I get this error @MEnnabah

**Comment by Shaheen-AlQaraghuli** [comment]
@NrmeenTomoum
When adding a beneficiary, you need to pass a name parameter in the JSON object.

**Comment by NrmeenTomoum** [comment]
[
<img width="1317" alt="Screen Shot 2020-09-20 at 5 39 49 PM" src="https://user-images.githubusercontent.com/19241793/93715206-49b52400-fb68-11ea-9251-32f24f51aefc.png">
](url)
@Shaheen-AlQaraghuli thanks for your fast response but as you see in screen shot I added name in DPCBeneficiaryInfo

**Comment by MEnnabah** [comment]
Hi @NrmeenTomoum 
Would you please verify which SDK version you're using?

I think this version is below v0.2.0

**Comment by NrmeenTomoum** [comment]
yes, version number : DapiConnect (0.1.18), I will upgrade and retry.

**Comment by MEnnabah** [comment]
Great! Please refer to the docs on the README.md file since the change from 0.1.x to 0.2.x is source breaking. Please let me know if you need any assistance.

**Comment by NrmeenTomoum** [comment]
Thanks @MEnnabah for your helpful support 👍👍👍
