### ISSUE TITLE
loading issue

### ISSUE THREAD

**Issue by NrmeenTomoum** [dapi-co/DapiConnect-iOS#4]
<img width="438" alt="Screen Shot 2020-09-20 at 7 54 43 PM" src="https://user-images.githubusercontent.com/19241793/93718250-221b8700-fb7b-11ea-87b0-4161acc9406c.png">
after I did link with ADCB I can't see my linked account, and when reopen I didn't found it in list even if I can fount it in client.data.getAccounts??? Any help..
(0.2.6)

**Comment by MEnnabah** [comment]
Hi @NrmeenTomoum 

I believe `connectDidSuccessfullyConnect(toBankID:userID:)` delegate method is not called yet. This usually happen if the the [SDK Server](https://docs.dapi.co/docs/sdk-server) (should be deployed on your server) is not responding.

The SDK Server should be configured and passed to DapiConnect SDK as follows:

```swift
var urlComponents = URLComponents(string: "https://yourserver.com/1234")!
let configuration = DapiConfigurations(appKey: appKey, baseUrl: urlComponents, countries: ["AE"], clientUserID: "Nermeen")
configuration.environment = .sandbox
let client = DapiClient(configurations: configuration)
```

Would you please verify if you have it configured?

**Comment by NrmeenTomoum** [comment]
yes and the calling for this delegate method connectDidSuccessfullyConnect  done successfully !!

**Comment by MEnnabah** [comment]
That’s weird to be happening. I’d like to schedule a Zoom call to debug this with you, please select one of the [available slots](https://calendly.com/ennabah/30min) that fits your schedule.
